name: ds2-coiled-2026
channels:
  - conda-forge
dependencies:
  - python = 3.11
  - xarray = 2025.9.0
  - hvplot = 0.12.2
  - gcsfs = 2025.12.0
  - intake = 2.0.8
  - intake-xarray = 2.0.0
  - zarr = 3.1.5
  - cartopy = 0.25.0
  - scikit-learn = 1.8.0
  - seaborn = 0.13.2
  - dask-ml = 2025.1.0
  - graphviz = 14.1.0
  - coiled = 1.130.0
#  - google-cloud-sdk = 550.0.0 # Installed manually because not available for Windows
  - ipykernel = 7.1.0
  - argopy = 1.4.0
  - s3fs = 2025.12.0
  - xarrayutils = 2.0.1
  - copernicusmarine = 2.2.5
  - gsw = 3.6.20

  - pip = 25.3
  - pip:
    - httpimport==1.4.1
    - coiled[notebook]
    - pyopenssl==24.3.0
    - msgpack==1.1.2
